name: QUIC Interop
on:
  schedule:
    # Every 12h at 03:15 UTC and 15:15 UTC.
    - cron: "15 3,15 * * *"

jobs:
  run:
    uses: ./.github/workflows/interop.yml
    with:
      protocol: quic
      implementations_file: implementations_quic.json
      upload_dir: ${{ vars.LOG_DIR_QUIC }}
      upload_results: true
      run_measurements: true
    secrets: inherit
