name: Linter
on:
  pull_request: 
    branches: [ master ]
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Linters
        run: pip3 install flake8 isort black
      - name: flake8
        run: flake8 *.py
      - name: isort
        run: isort -c -df *.py
      - name: black
        run: black --check --diff *.py
